-- /storage/emulated/0/Download/01 - VAULTS/r9cn/001 - CLASS VII/00 - INDEX - C - VII.sdr/metadata.md.lua
return {
    ["annotations"] = {},
    ["config_panel_index"] = 1,
    ["copt_b_page_margin"] = 20,
    ["copt_block_rendering_mode"] = 3,
    ["copt_cjk_width_scaling"] = 100,
    ["copt_embedded_css"] = 1,
    ["copt_embedded_fonts"] = 1,
    ["copt_font_base_weight"] = 0.5,
    ["copt_font_gamma"] = 15,
    ["copt_font_hinting"] = 2,
    ["copt_font_kerning"] = 3,
    ["copt_font_size"] = 30,
    ["copt_h_page_margins"] = {
        [1] = 70,
        [2] = 70,
    },
    ["copt_line_spacing"] = 100,
    ["copt_nightmode_images"] = 1,
    ["copt_render_dpi"] = 300,
    ["copt_rotation_mode"] = 0,
    ["copt_smooth_scaling"] = 0,
    ["copt_status_line"] = 1,
    ["copt_sync_t_b_page_margins"] = 0,
    ["copt_t_page_margin"] = 50,
    ["copt_view_mode"] = 0,
    ["copt_visible_pages"] = 1,
    ["copt_word_expansion"] = 0,
    ["copt_word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["cre_dom_version"] = 20240114,
    ["css"] = "./data/epub.css",
    ["doc_pages"] = 6,
    ["doc_path"] = "/storage/emulated/0/Download/01 - VAULTS/r9cn/001 - CLASS VII/00 - INDEX - C - VII.md",
    ["doc_props"] = {
        ["title"] = "00 - INDEX - C - VII",
    },
    ["floating_punctuation"] = 0,
    ["font_face"] = "Ko Bitter",
    ["font_family_fonts"] = {},
    ["handmade_flows_edit_enabled"] = true,
    ["handmade_flows_enabled"] = false,
    ["handmade_toc_edit_enabled"] = true,
    ["handmade_toc_enabled"] = false,
    ["hide_nonlinear_flows"] = false,
    ["highlight_color"] = "gray",
    ["highlight_drawer"] = "lighten",
    ["hyph_force_algorithmic"] = false,
    ["hyph_soft_hyphens_only"] = false,
    ["hyph_trust_soft_hyphens"] = false,
    ["hyphenation"] = true,
    ["inverse_reading_order"] = false,
    ["invert_ui_layout"] = false,
    ["last_xpointer"] = "/html/body/ul[3]/li[7]/a/text().23",
    ["page_overlap_style"] = "dim",
    ["partial_md5_checksum"] = "d8817f73b521d2c8a9532f0074047f42",
    ["partial_rerendering"] = true,
    ["percent_finished"] = 1,
    ["readermenu_tab_index"] = 1,
    ["show_overlap_enable"] = false,
    ["stats"] = {
        ["authors"] = "N/A",
        ["highlights"] = 0,
        ["language"] = "N/A",
        ["notes"] = 0,
        ["pages"] = 6,
        ["performance_in_pages"] = {},
        ["series"] = "N/A",
        ["title"] = "00 - INDEX - C - VII",
    },
    ["summary"] = {
        ["modified"] = "2026-10-03",
        ["status"] = "reading",
    },
    ["text_lang"] = "en-US",
    ["text_lang_embedded_langs"] = true,
    ["toc_ticks_ignored_levels"] = {},
}
